version: "3.9"  # optional since v1.27.0
services:
  db:
    image: 'postgres:latest'
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD_FILE: run/secrets/db_password
      POSTGRES_DB: 'projectbank'
    secrets:
      - db_password

  server:
    image: server
    build:
      context: .
      dockerfile: './Dockerfile'
    environment:
      ConnectionStrings__ProjectBank:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443/;http://+:80
      ASPNETCORE_HTTPS_PORT: 7207
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: localhost
    ports:
      - '5077:80'
      - '7207:443'
    depends_on:
      - db
    secrets:
      - source: connection_string
        target: ConnectionStrings__ProjectBank
    volumes:
      - '~/.aspnet/https/:/https/'

secrets:
  db_password:
    file: './.local/db_password.txt'
  connection_string:
    file: './.local/connection_string.txt'
  