// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectBank.Infrastructure;

#nullable disable

namespace ProjectBank.Infrastructure.Migrations
{
    [DbContext(typeof(ProjectBankContext))]
    [Migration("20211208132446_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectBank.Infrastructure.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("UniversityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("UniversityId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ProjectBank.Infrastructure.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("TagGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ProjectId");

                    b.HasIndex("TagGroupId");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("ProjectBank.Infrastructure.Entities.TagGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiredInProject")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupervisorCanAddTag")
                        .HasColumnType("boolean");

                    b.Property<int?>("TagLimit")
                        .HasColumnType("integer");

                    b.Property<int?>("UniversityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("UniversityId");

                    b.ToTable("TagGroups");
                });

            modelBuilder.Entity("ProjectBank.Infrastructure.Entities.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("ProjectBank.Infrastructure.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("UniversityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ProjectId");

                    b.HasIndex("UniversityId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProjectBank.Infrastructure.Entities.Project", b =>
                {
                    b.HasOne("ProjectBank.Infrastructure.Entities.University", null)
                        .WithMany("Projects")
                        .HasForeignKey("UniversityId");
                });

            modelBuilder.Entity("ProjectBank.Infrastructure.Entities.Tag", b =>
                {
                    b.HasOne("ProjectBank.Infrastructure.Entities.Project", null)
                        .WithMany("Tags")
                        .HasForeignKey("ProjectId");

                    b.HasOne("ProjectBank.Infrastructure.Entities.TagGroup", null)
                        .WithMany("Tags")
                        .HasForeignKey("TagGroupId");
                });

            modelBuilder.Entity("ProjectBank.Infrastructure.Entities.TagGroup", b =>
                {
                    b.HasOne("ProjectBank.Infrastructure.Entities.University", null)
                        .WithMany("TagGroups")
                        .HasForeignKey("UniversityId");
                });

            modelBuilder.Entity("ProjectBank.Infrastructure.Entities.User", b =>
                {
                    b.HasOne("ProjectBank.Infrastructure.Entities.Project", null)
                        .WithMany("Supervisors")
                        .HasForeignKey("ProjectId");

                    b.HasOne("ProjectBank.Infrastructure.Entities.University", null)
                        .WithMany("Users")
                        .HasForeignKey("UniversityId");
                });

            modelBuilder.Entity("ProjectBank.Infrastructure.Entities.Project", b =>
                {
                    b.Navigation("Supervisors");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("ProjectBank.Infrastructure.Entities.TagGroup", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("ProjectBank.Infrastructure.Entities.University", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("TagGroups");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
